# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rapt00r's Blog
email: rapt00rr@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Talking about Ethical Hacking, Information Security and Bug Bounty :)
  
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vitor-fernandes.github.io" # the base hostname & protocol for your site

#sidebar
default-image: profile.jpeg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: rapt00r

copyright:
   name: rapt00r
   link: 'https://vitor-fernandes.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: no
disqus-shortname: rapt00r

#social
twitter: http://twitter.com/@Rapt00rVF
email: rapt00rr@protonmail.com
facebook: https://www.facebook.com/ethicalhackersufpb/
telegram: https://t.me/rapt00r

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

